apiVersion: v1
kind: Pod
metadata:
  name: presto-cli
spec:
  containers:
  - name: presto-cli
    image: "uprush/prestosql-cli:340"
    # Just spin & wait forever
    command: [ "tail", "-f", "/dev/null" ]
